version: '3.8'

services:
  api:
    build:
      context: ./infra/docker
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  web:
    build:
      context: ./infra/docker
      dockerfile: Dockerfile.web
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://api:3000
    depends_on:
      - api

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: